version: '3.3'
volumes:
  grafana-storage:
  localstack:
  loki:

services:
  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    volumes:
      - "./grafana-storage:/var/lib/grafana"
  localstack:
    image: localstack/localstack-full
    command: ["unset http_proxy && unset https_proxy"]
    ports:
      - "4563-4599:4563-4599"
      - "8055:8080"
    environment:
      - SERVICES=s3,lambda,sqs
      - AWS_ACCESS_KEY_ID=123
      - AWS_SECRET_ACCESS_KEY=foobar
      - AWS_DEFAULT_REGION=sa-east-1
      - DATA_DIR=/tmp/localstack/data
      - START_WEB=1
    volumes:
      - "./localstack:/tmp/localstack"
      - /var/run/docker.sock:/var/run/docker.sock
  loki:
    image: grafana/loki:2.4.2
    ports:
      - "192.168.15.120:3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/config.yaml:/etc/loki/config.yaml
      - loki:/data/loki
    